
use_frameworks!
# Resolución de react_native_pods.rb con node para permitir hoisting
use_modular_headers!

# Asegúrate de colocar `use_frameworks!` para habilitar el enlace dinámico


require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Awesome76' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Ruta absoluta a la raíz de tu aplicación
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Añadir pods de Firebase
  pod 'FirebaseCore'
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )
  end
end
